### ISSUE TITLE
dotnet tool install command failing with "No executable found matching command" error.

### ISSUE THREAD

**Issue by smashedtoatoms** [emersonsoares/asdf-dotnet-core#1]
I am getting `No executable found matching command "dotnet-tool"` with 2.1.4 on mac when I run any `dotnet tool install` commands.  It should be supported.  Any ideas on what might be causing that?

**Comment by steventnorris-40AU** [comment]
I ran into a similar issue trying to run `dotnet --info` and getting `No such command in 2.2 of dotnet-core`. It seems like this may just include the runtime and not the sdk.

**Comment by steventnorris-40AU** [comment]
Figuring this out. In my case, there was another dotnet core version in /usr/local/share/dotnet that I had to remove. Then remove the asdf dotnet-core plugin and reinstall. Having a prior version borked the install. After that, all good to go.

**Comment by anthonyaoun23** [comment]
I solved this by downloading the latest .NET Core SDK. Found at https://dotnet.microsoft.com/download

**Comment by jthegedus** [comment]
Also worth noting, the versions have patch numbers of 3 digits or more. Run `asdf list-all dotnet-core` to see which versions are actually supported.
