### ISSUE TITLE
tail -r is present only on BSD (OSX)

### ISSUE THREAD

**Issue by gpad** [emersonsoares/asdf-dotnet-core#13]
I have create a PR #12 to fix this issue because `tail -r` is not present on unix/Linux systems only on BSD. So I have fixed using `tac` if `tail -r` is not present

**Comment by e12e** [comment]
Thank you for this - this fixes `list-all` for me, which is currently broken on the latest version (discovered after running a `asdf plugin-update dotnet-core`).

FYI - this means it's impossible to use `list-all` on most (all?) linux distributions until this is merged.

**Comment by emersonsoares** [comment]
PR merged!

Thanks 💯
