### ISSUE TITLE
Can't use multiple global versions

### ISSUE THREAD

**Issue by ericmilaneze** [emersonsoares/asdf-dotnet-core#16]
Hi,

I'm using Fedora 31 and trying to use multiple global versions of dotnet-core with no lucky.

Command:
`asdf global dotnet-core 3.1.101 2.2.207`

And then when runing this command:
`dotnet --info`

I've got:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /home/eric/.asdf/installs/dotnet-core/3.1.101/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/home/eric/.asdf/installs/dotnet-core/3.1.101/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/home/eric/.asdf/installs/dotnet-core/3.1.101/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/home/eric/.asdf/installs/dotnet-core/3.1.101/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
[eric@localhost ~]$ asdf global dotnet-core 3.1.101 2.2.207
[eric@localhost ~]$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /home/eric/.asdf/installs/dotnet-core/3.1.101/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/home/eric/.asdf/installs/dotnet-core/3.1.101/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/home/eric/.asdf/installs/dotnet-core/3.1.101/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/home/eric/.asdf/installs/dotnet-core/3.1.101/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Am I missing something or is this not possible to achieve?

**Comment by lzocateli00** [comment]
I have the same problem, I use ubuntu 20.04 and I have several dotnet core projects in several different sdk versions, I had to uninstall the asdf, as it does not help in this situation. If this problem is solved, then I use asdf, which was done to deal with situations like this.

**Comment by lzocateli00** [comment]
@ericmilaneze  you must execute this command inside the project folder that uses another version of the dotnet core, different from its global version: (in this example, I have 3.1.201 as global)
asdf local dotnet-core 2.2.110

A .tool-versions file will be created inside your folder where your project is, it works as a global.json, only to guide the asdf.

That is, you must have a .tool-versions within each folder of your projects or in a folder above.
