### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by Weffe** [emersonsoares/asdf-dotnet-core#2]
I am trying to install dotnet core 2.2 on Linux Mint 18.3 and I am running into an install issue. 

```bash
$ asdf install dotnet-core 2.2
Downloading the CLI installer
Installing the CLI requested version 2.2. Please wait, installation may take a few minutes.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2/dotnet-sdk-2.2-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2/dotnet-sdk-2.2-linux-x64.tar.gz
dotnet_install: Error: Could not download .NET Core SDK version 2.2
The CLI has been installed.
```

Even after it fails, it still appears as if it installs correctly and gets added to the adsf dotnet-core plugin as a "valid" version. I tried installing dotnet version 2.1 and 3.0 and ran into the same install error. 

Maybe the site which we are trying to download the tar.gz file from has moved?

**Comment by steventnorris-40AU** [comment]
@Weffe 2.2.101 is the version number. Try `asdf install dotnet-core 2.2.101`

**Comment by Weffe** [comment]
Thanks! That's my bad for not looking at the version correctly :sweat_smile:
