### ISSUE TITLE
dotnet core v3 preview4 is not available to install

### ISSUE THREAD

**Issue by gpad** [emersonsoares/asdf-dotnet-core#4]
The preview 4 of version 3 is already released https://github.com/dotnet/core/tree/master/release-notes/3.0 but it's not available to install with this plugin.
This plugin call this URL https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json and the version is not listed in this json.

Is the right URL to call to see the list of available version?

Is it a problem of .net CORE team that hadn't update the json?

**Comment by gpad** [comment]
@emersonsoares Have you been able to check this issue? I'm not able to install the last version. Is it my fault ???

**Comment by spartanroger** [comment]
Actually, I think this issue is related with the [dotnet core repo](https://github.com/dotnet/core/blob/aspnetcore30p7/release-notes/releases.json), as they should keep the file updated.

**Comment by gpad** [comment]
@emersonsoares I have found this issue https://github.com/dotnet/announcements/issues/87 I think that this package are checking an old deprecated file

**Comment by emersonsoares** [comment]
Hey! The package is looking into a deprecated file to discover available releases, as @gpad pointed in his comment, with dotnet/announcements#87. The plugin needs to start looking in `releases-index.json` file. 

I'm starting my vacations this week and will not be able to fix this in the next few days, so any help on this would be welcome. 🆘

**Comment by emersonsoares** [comment]
A first version: 

```bash
curl -s https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json | grep -Eo '\"releases.json\": \".*\"' | sed -e 's/\"releases.json\": \"//;s/\"//' | xargs curl -s | grep -Eo '\"release-version\": \".*\"' | sed -e 's/\"release-version\": \"//;s/\"//'
```

**Comment by spartanroger** [comment]
Enjoying the first week at my new job, managed to open a PR: 

https://github.com/emersonsoares/asdf-dotnet-core/pull/8

Please share any improvements I could make...

Cheers
